from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import HTMLResponse
import os
import shutil
import tempfile

from dotenv import load_dotenv
import opendataloader_pdf

# uv run uvicorn main_opendataloader:app --host 0.0.0.0 --port 8002 --app-dir src

load_dotenv()

app = FastAPI(
    title="API OpenDataLoader PDF Extraction",
    version="1.0.0",
    description="API for PDF processing using OpenDataLoader",
    openapi_url="/openapi.json",
    docs_url="/docs",
    redoc_url="/redoc"
)


@app.post("/extract")
def extract(pdf: UploadFile = File(...)):
    if pdf.content_type != "application/pdf":
        raise HTTPException(status_code=400, detail="Invalid file type. PDF required.")

    with tempfile.TemporaryDirectory() as tmpdir:
        input_pdf_path = os.path.join(tmpdir, pdf.filename)
        output_dir = os.path.join(tmpdir, "output")
        os.makedirs(output_dir)

        with open(input_pdf_path, "wb") as f:
            shutil.copyfileobj(pdf.file, f)

        hybrid_url = os.getenv("OPENDATALOADER_HYBRID_URL", "http://localhost:5002")
        try:
            opendataloader_pdf.convert(
                input_path=[input_pdf_path],
                output_dir=output_dir,
                format="html",
                hybrid="docling-fast",
                hybrid_url=hybrid_url,
            )
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Extraction failed: {e}")

        stem = os.path.splitext(pdf.filename)[0]
        output_file = os.path.join(output_dir, f"{stem}.html")

        if not os.path.exists(output_file):
            raise HTTPException(status_code=500, detail="No output file generated by opendataloader")

        with open(output_file, "r", encoding="utf-8") as f:
            html_content = f.read()

    return HTMLResponse(content=html_content)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
